### ISSUE TITLE
Milestone 1 Report

### ISSUE THREAD

**Issue by OwenBC** [realjaidhaliwal/game-of-life-modern-java#1]
1. Introduction (describe the chosen project, what does the system do, where did you find it, why did you select it)
2. Migration to CI (describe which changes you had to make to move it to GitHub CI, which challenges did you encounter and how did you save these challenges.)
3. Explain the CI workflows you have set up.
4. CI Change Scenario (describe a sample scenario with screen shots that shows the CI workflows at work)
5. Team work log (describe a log book of all work that team members performed on this project, including times and tasks performed.)

**Comment by OwenBC** [comment]
Introduction section has been drafted by @ketdougi.

I've added a table for the work log section.

**Comment by ketdougi** [comment]
I will start working on Section 2 of the report. I will write about the build not working due to their being no webdriver. Is there any other problems that was encountered when setting up the CI?

Also would you @OwenBC @realjaidhaliwal want to split up Sections 3 & 4? 

Make sure everyone adds what they have done to the work log!!

**Comment by vijaivir** [comment]
@OwenBC updated Section 3 and I have added some screenshots in section 4. Please review the section and let me know if any changes or more details are required @ketdougi @OwenBC

**Comment by ketdougi** [comment]
All report sections completed.
